### PR TITLE
Updated for Flutter v1.5.4-hotfix.2

### PR DESCRIPTION
**Pull request by akassharjun**
Please update the sha256 like last time. I couldn't find it on the flutter.dev webpage.

### CODE REVIEW

**Comment by akassharjun** [comment]
Oh and I've forgotten to pull the sha256 changes you made before.

**Comment by fbsb** [comment]
Thank you!

I updated the checksum and resolved the conflicts. Please make sure to pull my changes back.

**Comment by akassharjun** [comment]
Sure! Could you tell me how I could find the checksum? 🤣 (For the next time)

**Comment by fbsb** [comment]
You could either download the file and then `sha256sum` the file or you could `brew cask fetch flutter` then let brew complain about the hashes not matching and then update the checksum accordingly.

**Pull request merged**
